language: go

before_install:
  - go get -t -v ./...

script:
  - cd doublylinkedlist
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - cd ../lrucache
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)